/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package robot

import kotlin.test.Test
import kotlin.test.*

class AppTest {
    private val app = App()

    @Test fun `should say hello to John Armless`() {
        val name = "John Armless"
        assertEquals(app.hello(name), "Hello ${name}")
    }

    @Test fun `should number is even`() {
        val param = 4
        assertTrue(app.isEven(param))
    }
    @Test fun `should number is odd`() {
        val param = 5
        assertFalse(app.isEven(param))
    }

    @Test fun `should return true when palindroma`() {
        var word = "arara";
        assertTrue(app.isPalindroma(word))
    }

    @Test fun `should return false when not palindroma`() {
        var word = "test";
        assertFalse(app.isPalindroma(word))
    }
}
