/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package robot

class App {
    fun hello(name: String): String {
        return "Hello ${name}"
    }

    fun isEven(numberParam: Int): Boolean {
        return numberParam % 2 == 0
    }

    fun isPalindroma(word: String): Boolean {
        val count = word.length - 1

        for(i in 0..(count / 2)){
            if(word.elementAt(i) != word.elementAt(count - i)) {
                return false
            }
        }

        return true
    }
}
